import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file will be generated by flutterfire configure
import 'package:firebase_auth/firebase_auth.dart'; // Import Firebase Auth
import 'package:flutter_chat_mvp/pages/login_page.dart'; // We'll create this
import 'package:flutter_chat_mvp/pages/home_page.dart'; // And this

void main() async {
  // Ensure that Flutter bindings are initialized. This is necessary before calling any Firebase services.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the options for the current platform (Android/iOS).
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Run the app.
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Chat MVP',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: StreamBuilder<User?>(
        // Listen for changes in authentication state
        stream:
            FirebaseAuth.instance
                .authStateChanges(), // This stream emits a User object when the user signs in or out
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            // While checking the authentication state, show a loading indicator
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          } else if (snapshot.hasData) {
            // If the snapshot has data, it means the user is signed in
            return const HomePage();
          } else {
            // Otherwise, the user is not signed in, so show the login page
            return const LoginPage();
          }
        },
      ),
    );
  }
}
